name: mimic-pipeline
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - numpy
  - xgboost
  - tqdm
  - scikit-learn
  - ipywidgets
  - imbalanced-learn
  - pytorch
  - nltk
  - requests
  - pip
  - pip:
      - import-ipynb
      - captum
      - pytorch_pretrained_bert
      - nltk
      - PyRuSH
      - medspacy
      - pydicom